import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	const [data, setData] = useState({ text: "" });
	const [query, setQuery] = useState();
	const [search, setSearch] = useState();
	const [isLoading, setIsLoading] = useState(false);

	useEffect(() => {
		const fetchData = async () => {
			if (search) {
				setIsLoading(true);
				const resp = await fetch(`/api/openai`, {
					body: JSON.stringify({
						name: search,
					}),
					headers: {
						"Content-Type": "application/json",
					},
					method: "POST",
				});

				const data = await resp.json();
				setData(data);
				setIsLoading(false);
			}
		};

		fetchData();
	}, [search]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					<a>AI Lyrics Generator</a>
				</h1>

				<p className={styles.description}>
					Built with NextJS & GPT-3 API
				</p>

				<div className={styles.grid}>
					<div className={styles.card}>
						<h2>Enter Artist Name;</h2>
						<input
							type="text"
							value={query}
							onChange={(e) => setQuery(e.target.value)}
						/>

						<button type="button" onClick={() => setSearch(query)}>
							Generate
						</button>

						<h4>Lyrics</h4>
						{isLoading ? (
							<div>Loading....</div>
						) : (
							<span>{data.text}</span>
						)}
					</div>
				</div>
			</main>
		</div>
	);
}
